version: "3.7"
services:
  docker-on-demand:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker_on_demand
    ports:
      - 1337:1337
    environment:
      - WORKERS=4
      - DATA_FOLDER=/var/data
      - LOG_FOLDER=/var/log/docker-on-demand
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    volumes:
      - docker-on-demand-logs:/var/log/docker-on-demand
      - docker-on-demand-data:/var/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  docker-on-demand-data:
    name: docker-on-demand-data
  docker-on-demand-logs:
    name: docker-on-demand-logs
